=== royfochtman/WBA2_Phase2/bin/main/webapp/WEB-INF/xml/xml_schema_files/job.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/photoBay"  xmlns:job="http://www.example.org/photoBay" elementFormDefault="qualified">
<xs:include schemaLocation="topic.xsd"></xs:include>
<!-- definition of attributes -->


<!-- definition of complex elements -->
<xs:element name="job">
	
	<xs:complexType>
		
		<xs:all maxOccurs="1" minOccurs="1">
		
			<xs:element name="jobName" type="xs:string"></xs:element>
			<xs:element name="urgency" type="xs:string"></xs:element>
			<xs:element name="deadline" type="xs:date"></xs:element>
			<xs:element name="description" type="xs:string"></xs:element>
			<xs:element name="payment" type="xs:positiveInteger"></xs:element>
			<xs:element name="topics" type="job:topicType"></xs:element>
			<xs:element name="status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="new"></xs:enumeration>
						<xs:enumeration value="assigned"></xs:enumeration>
						<xs:enumeration value="closed"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>	
			</xs:element>
			
		</xs:all> 
		<xs:attribute name="ID" type="xs:int" use="required"/>
		<xs:attribute name="ref" type="xs:anyURI" use="required"/>
		<xs:attribute name="pressAgencyRef" type="xs:anyURI" use="required"/>
		<xs:attribute name="dateOfCreation" type="xs:date" use="required"></xs:attribute>
	</xs:complexType>
</xs:element>

</xs:schema>

=== royfochtman/WBA2_Phase2/src/main/webapp/WEB-INF/xml/xml_test/jobTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<job:job dateOfCreation="2001-01-01" job:ID="0" pressAgencyID="0" xmlns:job="http://www.example.org/photoBay" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/photoBay ../xml_schema_files/job.xsd ">
  <job:jobName>job:jobName</job:jobName>
  <job:urgency>job:urgency</job:urgency>
  <job:deadline>2001-01-01</job:deadline>
  <job:description>job:description</job:description>
  <job:payment>1</job:payment>
  <job:topics>
    <job:topicName>Sport</job:topicName>
  </job:topics>
  <job:status>new</job:status>
</job:job>

=== royfochtman/WBA2_Phase2/src/main/webapp/WEB-INF/xml/xml_test/job.xml
<?xml version="1.0" encoding="UTF-8"?>
<job:job ID="0" dateOfCreation="2001-01-01" pressAgencyRef="http://tempuri.org" ref="http://tempuri.org" xmlns:job="http://www.example.org/photoBay" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/photoBay ../xml_schema_files/job.xsd ">
  <job:jobName>job:jobName</job:jobName>
  <job:urgency>job:urgency</job:urgency>
  <job:deadline>2001-01-01</job:deadline>
  <job:description>job:description</job:description>
  <job:payment>1</job:payment>
  <job:topics>
    <job:topicName>Sport</job:topicName>
  </job:topics>
  <job:status>new</job:status>
</job:job>
