=== royfochtman/WBA2_Phase2/bin/main/webapp/WEB-INF/xml/xml_schema_files/job_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/photoBay"  xmlns:job="http://www.example.org/photoBay" elementFormDefault="qualified">

<!-- definition of simple elements -->
<!--  
<xs:element name="jobName" type="xs:string"></xs:element>
<xs:element name="theme" type="xs:string"></xs:element>
<xs:element name="urgency" type="xs:string"></xs:element>
<xs:element name="dateOfCreation" type="xs:date"></xs:element>
<xs:element name="deadline" type="xs:date"></xs:element>
<xs:element name="description" type="xs:string"></xs:element>
<xs:element name="payment" type="xs:positiveInteger"></xs:element>
-->

<!-- definition of attributes -->
<xs:attribute name="jobID" type="xs:int" />
<!-- <xs:attribute name="pressID" type="xs:int"/> -->

<!-- definition of complex elements -->
<xs:element name="job">
	
	<xs:complexType>
		
		<xs:all maxOccurs="1" minOccurs="1">
		<!--  
			<xs:element ref="job:jobName"></xs:element>
			<xs:element ref="job:theme"></xs:element>
			<xs:element ref="job:urgency"></xs:element>
			<xs:element ref="job:deadline"></xs:element>
			<xs:element ref="job:description"></xs:element>
			<xs:element ref="job:payment"></xs:element>	
			<xs:element ref="job:dateOfCreation"></xs:element>	
			-->
			
			<xs:element name="jobName" type="xs:string"></xs:element>
			<xs:element name="theme" type="xs:string"></xs:element>
			<xs:element name="urgency" type="xs:string"></xs:element>
			<xs:element name="dateOfCreation" type="xs:date"></xs:element>
			<xs:element name="deadline" type="xs:date"></xs:element>
			<xs:element name="description" type="xs:string"></xs:element>
			<xs:element name="payment" type="xs:positiveInteger"></xs:element>
			<xs:element name="status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="new"></xs:enumeration>
						<xs:enumeration value="assigned"></xs:enumeration>
						<xs:enumeration value="closed"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>	
			</xs:element>
			
		</xs:all> 
		<xs:attribute ref="job:jobID" use="required"/>
		<!-- Es muss noch entschieden werden, ob die pressID hier auch verfÃ¼gbar sein soll. Wenn ja, dann muss es auf die ID der Presse referenzieren -->
		<!-- <xs:attribute ref="job:pressID" use="required"/> -->
	</xs:complexType>
</xs:element>

</xs:schema>

=== royfochtman/WBA2_Phase2/src/main/webapp/WEB-INF/xml/xml_files/job_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<job:job job:jobID="0" xmlns:job="http://www.example.org/photoBay" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/photoBay ../xml_schema_files/job_schema.xsd ">
  <job:jobName>job:jobName</job:jobName>
  <job:theme>job:theme</job:theme>
  <job:urgency>job:urgency</job:urgency>
  <job:dateOfCreation>2001-01-01</job:dateOfCreation>
  <job:deadline>2001-01-01</job:deadline>
  <job:description>job:description</job:description>
  <job:payment>1</job:payment>
</job:job>
